theme = "dark_plus"

[editor]
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[keys.normal]
"0" = "goto_line_start"
"$" = "goto_line_end"

[keys.select]
"0" = "goto_line_start"
"$" = "goto_line_end"
"A-x" = "extend_line_above"
