theme = "dark_plus"

[editor]
# line-number = "relative"

[keys.normal]
"0" = "goto_line_start"
"$" = "goto_line_end"

[keys.select]
"0" = "goto_line_start"
"$" = "goto_line_end"
"A-x" = "extend_line_above"
