return {
	{ "rhaiscript/vim-rhai", ft = "rhai" },
	-- {
	-- 	"mrcjkb/rustaceanvim",
	-- 	version = "^6",
	-- 	lazy = false,
	-- 	ft = { "rust" },
	-- 	opts = {
	-- 		server = {
	-- 			on_attach = function(client, bufnr)
	-- 				vim.api.nvim_set_hl(0, "LspInlayHint", { fg = "#575B6E", italic = true })
	-- 				vim.lsp.inlay_hint.enable(true, { bufnr = bufnr })
	-- 			end,
	-- 			capabilities = {
	-- 				offsetEncoding = { "utf-8", "utf-16" },
	-- 				positionEncodings = { "utf-8", "utf-16" },
	-- 			},
	-- 			default_settings = {
	-- 				["rust-analyzer"] = {
	-- 					cargo = {
	-- 						allFeatures = true,
	-- 						targetDir = "target/rust-analyzer",
	-- 						extraEnv = { RUSTFLAGS = "-C debuginfo=0" },
	-- 					},
	-- 					checkOnSave = {
	-- 						enable = true,
	-- 						command = "check",
	-- 						extraArgs = { "--target-dir", "target/rust-analyzer" },
	-- 					},
	-- 					files = {
	-- 						excludeDirs = {
	-- 							".git",
	-- 							".venv",
	-- 							".terraform",
	-- 							"target",
	-- 							"node_modules",
	-- 							"gistia-design-system/node_modules",
	-- 						},
	-- 						watcher = "client",
	-- 					},
	-- 					diagnostics = {
	-- 						enable = true,
	-- 						experimental = { enable = false },
	-- 						refreshSupport = false,
	-- 					},
	-- 					procMacro = {
	-- 						ignored = {
	-- 							leptos_macro = { "server" },
	-- 						},
	-- 					},
	-- 					cache = { warmup = true },
	-- 					workspace = { refreshTime = 150 },
	-- 					buildScripts = {
	-- 						enable = true,
	-- 						rebuildOnSave = false,
	-- 					},
	-- 				},
	-- 			},
	-- 		},
	-- 	},
	-- 	config = function(_, opts)
	-- 		vim.g.rustaceanvim = opts
	-- 	end,
	-- },
}
